### ISSUE TITLE
SortedList gets confused by NaN values

### ISSUE THREAD

**Issue by rumpeltux** [grantjenks/sorted_containers#73] opened 2017-09-23 15:44 UTC
```python
>>> import sortedcontainers
>>> import numpy as np
>>> y = sortedcontainers.SortedList()
>>> y.append(np.NaN)
>>> y.remove(np.NaN)
/usr/lib/python3/dist-packages/sortedcontainers/sortedlist.py in remove(self, val)
    260             self._delete(pos, idx)
    261         else:
--> 262             raise ValueError('{0} not in list'.format(repr(val)))
    263 
    264     def _delete(self, pos, idx):
ValueError: nan not in list
>>> y.append(1)
>>> y.remove(1)
ValueError: 1 not in list
```

Accordingly SortedDict also doesn’t work anymore if NaN values are present.

**Comment by grantjenks** [comment] 2017-09-23 16:10
I think this is expected behavior. NaNs violate the total ordering requirement of sorted collections types. NaNs do not compare equal to one another. They are also not orderable. I don't think we can support them.

Regular Python lists don't have this problem because they check both identity and equality.

**Comment by rumpeltux** [comment] 2017-09-23 21:06
Fair enough, can this be added to the documentation?
Potentially causing an error already during the append operation?

**Comment by grantjenks** [comment] 2017-09-23 21:36
Yes, I agree, it's worth describing the limitation in the documentation.

I'm not sure we can catch the situation that easily. Would math.isnan(...) return True for np.NaN? I don't want to add a dependency on numpy. I'm also not sure I want to check every value that is added and slowdown a very common operation. The last issue is that float values define comparison operators so we can't just check those exist (which has been suggested before).

**Comment by grantjenks** [comment] 2017-09-23 21:36
Duplicate of #64

**Closed by grantjenks** 2017-09-23 21:36 UTC
